server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/librarydb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true